name: Build and Release Image Stamper

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller  # Explicitly install PyInstaller

      # Step 4: Build Executable with PyInstaller
      - name: Build Executable
        run: |
          pyinstaller --onefile --windowed --icon=icon.icns --name "ImageStamper" main.py

      # Step 5: Upload Windows Executable as Artifact
      - name: Upload Windows Executable
        uses: actions/upload-artifact@v3
        with:
          name: ImageStamper-windows
          path: ./dist/ImageStamper.exe

  build-macos:
    name: Build macOS Executable (Universal2)
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Download and Install Universal2 Python
      - name: Download Universal2 Python 3.10
        run: |
          curl -O https://www.python.org/ftp/python/3.10.13/python-3.10.13-macos11-universal2.pkg

      - name: Install Universal2 Python 3.10
        run: |
          sudo installer -pkg python-3.10.13-macos11-universal2.pkg -target /

      # Step 3: Verify Python Installation
      - name: Verify Python Installation
        run: |
          /usr/local/bin/python3 --version
          /usr/local/bin/python3 -m pip --version

      # Step 4: Install dependencies using universal2 Python
      - name: Install Dependencies
        run: |
          /usr/local/bin/python3 -m pip install --upgrade pip
          /usr/local/bin/python3 -m pip install -r requirements.txt
          /usr/local/bin/python3 -m pip install pyinstaller  # Explicitly install PyInstaller

      # Step 5: Build Executable with PyInstaller
      - name: Build Executable
        run: |
          /usr/local/bin/pyinstaller --onefile --windowed --icon=icon.icns --name "ImageStamper" main.py

      # Step 6: Upload macOS Executable as Artifact
      - name: Upload macOS Executable
        uses: actions/upload-artifact@v3
        with:
          name: ImageStamper-macos
          path: ./dist/ImageStamper  # No extension on macOS

  release:
    name: Create GitHub Release
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download Windows Executable Artifact
      - name: Download Windows Executable
        uses: actions/download-artifact@v3
        with:
          name: ImageStamper-windows
          path: ./windows

      # Step 2: Download macOS Executable Artifact
      - name: Download macOS Executable
        uses: actions/download-artifact@v3
        with:
          name: ImageStamper-macos
          path: ./macos

      # Step 3: Create Git Tag
      - name: Create Git Tag
        id: create_tag
        shell: bash
        run: |
          # Generate a tag name using the short commit SHA
          TAG_NAME="build-${GITHUB_SHA::7}"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      # Step 4: Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: "Build ${{ env.TAG_NAME }}"
          draft: false
          prerelease: false

      # Step 5: Upload Windows Executable to Release
      - name: Upload Windows Executable to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows/ImageStamper.exe
          asset_name: ImageStamper-windows.exe
          asset_content_type: application/octet-stream

      # Step 6: Upload macOS Executable to Release
      - name: Upload macOS Executable to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./macos/ImageStamper
          asset_name: ImageStamper-macos
          asset_content_type: application/octet-stream
